# Generated by Django 5.0.9 on 2024-09-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stockmovement_date_and_more'),
        ('stocks', '0006_meta_product_minimum_order_quantity_and_more'),
    ]

    operations = [
    ]
