# Generated by Django 5.0.9 on 2024-09-19 08:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_merge_20240919_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 19, 8, 44, 24, 573889, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 9, 19, 8, 44, 24, 573900, tzinfo=datetime.timezone.utc))),
                ('bar_code', models.CharField(default='', max_length=100)),
                ('qr_code', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='date',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 8, 44, 24, 573680, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 8, 44, 24, 574964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.metainfo'),
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
